version: '3.9'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DATABASE_NAME=scheduler
      - DATABASE_USER=scheduler_user
      - DATABASE_PASSWORD=scheduler_pass
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: scheduler
      POSTGRES_USER: scheduler_user
      POSTGRES_PASSWORD: scheduler_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
